/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;

namespace GlobalMilesAirlineAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum AwardTypeEnum
    {
        DISTANCE_BASED, //TODO: Write general description for this method
        FARE_BASED, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type AwardTypeEnum
    /// </summary>
    public static class AwardTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "distance_based", "fare_based" };

        /// <summary>
        /// Converts a AwardTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The AwardTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(AwardTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case AwardTypeEnum.DISTANCE_BASED:
                case AwardTypeEnum.FARE_BASED:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of AwardTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of AwardTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<AwardTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into AwardTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed AwardTypeEnum value</returns>
        public static AwardTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type AwardTypeEnum", value));

            return (AwardTypeEnum) index;
        }
    }
} 