/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;

namespace GlobalMilesAirlineAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum CabinTypeEnum
    {
        UNKNOWN, //Unknown
        DISCOUNT_ECONOMY, //Discount Economy
        ECONOMY, //Economy
        FULL_ECONOMY, //Full Economy
        PREMIUM_ECONOMY, //Premium Economy
        DISCOUNT_BUSINESS, //Discount Business
        BUSINESS, //Business
        PREMIUM_BUSINESS, //Premium Business
        FIRST, //First
        PREMIUM_FIRST, //Premium First
    }

    /// <summary>
    /// Helper for the enum type CabinTypeEnum
    /// </summary>
    public static class CabinTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "unknown", "discount_economy", "economy", "full_economy", "premium_economy", "discount_business", "business", "premium_business", "first", "premium_first" };

        /// <summary>
        /// Converts a CabinTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The CabinTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(CabinTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case CabinTypeEnum.UNKNOWN:
                case CabinTypeEnum.DISCOUNT_ECONOMY:
                case CabinTypeEnum.ECONOMY:
                case CabinTypeEnum.FULL_ECONOMY:
                case CabinTypeEnum.PREMIUM_ECONOMY:
                case CabinTypeEnum.DISCOUNT_BUSINESS:
                case CabinTypeEnum.BUSINESS:
                case CabinTypeEnum.PREMIUM_BUSINESS:
                case CabinTypeEnum.FIRST:
                case CabinTypeEnum.PREMIUM_FIRST:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of CabinTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of CabinTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<CabinTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into CabinTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed CabinTypeEnum value</returns>
        public static CabinTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type CabinTypeEnum", value));

            return (CabinTypeEnum) index;
        }
    }
} 