/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;

namespace GlobalMilesAirlineAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum ExtraInfoTypeEnum
    {
        NATIONALITY, //Nationality
        NATIONAL_ID_NUMBER, //National ID Number
        LANGUAGE, //Language
        GENDER, //Gender
        BIRTHDAY, //Birthday
        ACADEMIC_TITLE, //Academic Title
        ADDRESS, //Address
        COUNTRY, //Country
        CITY, //City
        AREA, //Area
        ZIP_CODE, //Zip Code
        PASSWORD, //Password
    }

    /// <summary>
    /// Helper for the enum type ExtraInfoTypeEnum
    /// </summary>
    public static class ExtraInfoTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "nationality", "national_id_number", "language", "gender", "birthday", "academic_title", "address", "country", "city", "area", "zip_code", "password" };

        /// <summary>
        /// Converts a ExtraInfoTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The ExtraInfoTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(ExtraInfoTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case ExtraInfoTypeEnum.NATIONALITY:
                case ExtraInfoTypeEnum.NATIONAL_ID_NUMBER:
                case ExtraInfoTypeEnum.LANGUAGE:
                case ExtraInfoTypeEnum.GENDER:
                case ExtraInfoTypeEnum.BIRTHDAY:
                case ExtraInfoTypeEnum.ACADEMIC_TITLE:
                case ExtraInfoTypeEnum.ADDRESS:
                case ExtraInfoTypeEnum.COUNTRY:
                case ExtraInfoTypeEnum.CITY:
                case ExtraInfoTypeEnum.AREA:
                case ExtraInfoTypeEnum.ZIP_CODE:
                case ExtraInfoTypeEnum.PASSWORD:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of ExtraInfoTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of ExtraInfoTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<ExtraInfoTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into ExtraInfoTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed ExtraInfoTypeEnum value</returns>
        public static ExtraInfoTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type ExtraInfoTypeEnum", value));

            return (ExtraInfoTypeEnum) index;
        }
    }
} 