/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class FlightMin : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string pnr;
        private string ticketNumber;
        private string flightNumber;

        /// <summary>
        /// Passenger name record of the flight.
        /// </summary>
        [JsonProperty("pnr")]
        public string Pnr 
        { 
            get 
            {
                return this.pnr; 
            } 
            set 
            {
                this.pnr = value;
                onPropertyChanged("Pnr");
            }
        }

        /// <summary>
        /// Ticket number of the passenger.
        /// </summary>
        [JsonProperty("ticket_number")]
        public string TicketNumber 
        { 
            get 
            {
                return this.ticketNumber; 
            } 
            set 
            {
                this.ticketNumber = value;
                onPropertyChanged("TicketNumber");
            }
        }

        /// <summary>
        /// Number of the flight.
        /// </summary>
        [JsonProperty("flight_number")]
        public string FlightNumber 
        { 
            get 
            {
                return this.flightNumber; 
            } 
            set 
            {
                this.flightNumber = value;
                onPropertyChanged("FlightNumber");
            }
        }
    }
} 