/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class FlightCreateRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.AwardMilesRules awardMilesRules;
        private Models.PassengerMax passenger;
        private Models.RoutingTypeEnum routingType;
        private List<Models.FlightMax> flights;

        /// <summary>
        /// A complex object for definition of the award mile calculation logic.
        /// </summary>
        [JsonProperty("award_miles_rules")]
        public Models.AwardMilesRules AwardMilesRules 
        { 
            get 
            {
                return this.awardMilesRules; 
            } 
            set 
            {
                this.awardMilesRules = value;
                onPropertyChanged("AwardMilesRules");
            }
        }

        /// <summary>
        /// A complex object for representing a passenger.
        /// </summary>
        [JsonProperty("passenger")]
        public Models.PassengerMax Passenger 
        { 
            get 
            {
                return this.passenger; 
            } 
            set 
            {
                this.passenger = value;
                onPropertyChanged("Passenger");
            }
        }

        /// <summary>
        /// Routing type of the flights.
        /// </summary>
        [JsonProperty("routing_type", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.RoutingTypeEnum RoutingType 
        { 
            get 
            {
                return this.routingType; 
            } 
            set 
            {
                this.routingType = value;
                onPropertyChanged("RoutingType");
            }
        }

        /// <summary>
        /// An array of flights. We are expecting one flight for one way trip and two flights for round trip.
        /// </summary>
        [JsonProperty("flights")]
        public List<Models.FlightMax> Flights 
        { 
            get 
            {
                return this.flights; 
            } 
            set 
            {
                this.flights = value;
                onPropertyChanged("Flights");
            }
        }
    }
} 