/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class FlightSimple : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string airline;
        private string pnr;
        private string departureDate;
        private string departureAirport;
        private string arrivalAirport;

        /// <summary>
        /// IATA code for airline company.
        /// </summary>
        [JsonProperty("airline")]
        public string Airline 
        { 
            get 
            {
                return this.airline; 
            } 
            set 
            {
                this.airline = value;
                onPropertyChanged("Airline");
            }
        }

        /// <summary>
        /// Passenger name record of the flight.
        /// </summary>
        [JsonProperty("pnr")]
        public string Pnr 
        { 
            get 
            {
                return this.pnr; 
            } 
            set 
            {
                this.pnr = value;
                onPropertyChanged("Pnr");
            }
        }

        /// <summary>
        /// ISO 8601 date for departure time.
        /// </summary>
        [JsonProperty("departure_date")]
        public string DepartureDate 
        { 
            get 
            {
                return this.departureDate; 
            } 
            set 
            {
                this.departureDate = value;
                onPropertyChanged("DepartureDate");
            }
        }

        /// <summary>
        /// IATA code for the departure airport.
        /// </summary>
        [JsonProperty("departure_airport")]
        public string DepartureAirport 
        { 
            get 
            {
                return this.departureAirport; 
            } 
            set 
            {
                this.departureAirport = value;
                onPropertyChanged("DepartureAirport");
            }
        }

        /// <summary>
        /// IATA code for the  arrival airport.
        /// </summary>
        [JsonProperty("arrival_airport")]
        public string ArrivalAirport 
        { 
            get 
            {
                return this.arrivalAirport; 
            } 
            set 
            {
                this.arrivalAirport = value;
                onPropertyChanged("ArrivalAirport");
            }
        }
    }
} 