/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class FlightStatusRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.PassengerMin passenger;
        private Models.FlightMin flight;

        /// <summary>
        /// A complex object for representing passenger.
        /// </summary>
        [JsonProperty("passenger")]
        public Models.PassengerMin Passenger 
        { 
            get 
            {
                return this.passenger; 
            } 
            set 
            {
                this.passenger = value;
                onPropertyChanged("Passenger");
            }
        }

        /// <summary>
        /// A complex object for flight.
        /// </summary>
        [JsonProperty("flight")]
        public Models.FlightMin Flight 
        { 
            get 
            {
                return this.flight; 
            } 
            set 
            {
                this.flight = value;
                onPropertyChanged("Flight");
            }
        }
    }
} 