/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class FlightStatusResponse : Response 
    {
        // These fields hold the values for the public properties.
        private Models.FlightStatusTypeEnum flightStatus;
        private Models.FlightMax flight;

        /// <summary>
        /// The final status of flight. The possible values are 'used', 'unused' and 'reissued'. For the reissued tickets the following new flight information must provided.
        /// </summary>
        [JsonProperty("flight_status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.FlightStatusTypeEnum FlightStatus 
        { 
            get 
            {
                return this.flightStatus; 
            } 
            set 
            {
                this.flightStatus = value;
                onPropertyChanged("FlightStatus");
            }
        }

        /// <summary>
        /// A complex for the flight. It is only accepted for reissued status.
        /// </summary>
        [JsonProperty("flight")]
        public Models.FlightMax Flight 
        { 
            get 
            {
                return this.flight; 
            } 
            set 
            {
                this.flight = value;
                onPropertyChanged("Flight");
            }
        }
    }
} 