/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;

namespace GlobalMilesAirlineAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum GenderTypeEnum
    {
        MALE, //Male
        FEMALE, //Female
        UNKNOWN, //Unknown
    }

    /// <summary>
    /// Helper for the enum type GenderTypeEnum
    /// </summary>
    public static class GenderTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "male", "female", "unknown" };

        /// <summary>
        /// Converts a GenderTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The GenderTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(GenderTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case GenderTypeEnum.MALE:
                case GenderTypeEnum.FEMALE:
                case GenderTypeEnum.UNKNOWN:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of GenderTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of GenderTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<GenderTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into GenderTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed GenderTypeEnum value</returns>
        public static GenderTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type GenderTypeEnum", value));

            return (GenderTypeEnum) index;
        }
    }
} 