/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class MemberSearchResponse : Response 
    {
        // These fields hold the values for the public properties.
        private Models.TierTypeEnum tierType;
        private int baseMiles;
        private int promoMiles;

        /// <summary>
        /// Type of tiers.
        /// </summary>
        [JsonProperty("tier_type", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.TierTypeEnum TierType 
        { 
            get 
            {
                return this.tierType; 
            } 
            set 
            {
                this.tierType = value;
                onPropertyChanged("TierType");
            }
        }

        /// <summary>
        /// Value of current miles.
        /// </summary>
        [JsonProperty("base_miles")]
        public int BaseMiles 
        { 
            get 
            {
                return this.baseMiles; 
            } 
            set 
            {
                this.baseMiles = value;
                onPropertyChanged("BaseMiles");
            }
        }

        /// <summary>
        /// Value of status miles.
        /// </summary>
        [JsonProperty("promo_miles")]
        public int PromoMiles 
        { 
            get 
            {
                return this.promoMiles; 
            } 
            set 
            {
                this.promoMiles = value;
                onPropertyChanged("PromoMiles");
            }
        }
    }
} 