/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class MemberSearchRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string ffpNumber;
        private string firstName;
        private string lastName;

        /// <summary>
        /// FFP number of member
        /// </summary>
        [JsonProperty("ffp_number")]
        public string FfpNumber 
        { 
            get 
            {
                return this.ffpNumber; 
            } 
            set 
            {
                this.ffpNumber = value;
                onPropertyChanged("FfpNumber");
            }
        }

        /// <summary>
        /// First name
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName 
        { 
            get 
            {
                return this.firstName; 
            } 
            set 
            {
                this.firstName = value;
                onPropertyChanged("FirstName");
            }
        }

        /// <summary>
        /// Last name
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName 
        { 
            get 
            {
                return this.lastName; 
            } 
            set 
            {
                this.lastName = value;
                onPropertyChanged("LastName");
            }
        }
    }
} 