/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class NewMemberRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.User user;
        private Models.FlightSimple flight;

        /// <summary>
        /// A complex object for representing a user.
        /// </summary>
        [JsonProperty("user")]
        public Models.User User 
        { 
            get 
            {
                return this.user; 
            } 
            set 
            {
                this.user = value;
                onPropertyChanged("User");
            }
        }

        /// <summary>
        /// A complex object for flight.
        /// </summary>
        [JsonProperty("flight")]
        public Models.FlightSimple Flight 
        { 
            get 
            {
                return this.flight; 
            } 
            set 
            {
                this.flight = value;
                onPropertyChanged("Flight");
            }
        }
    }
} 