/*
 * GlobalMilesAirlineAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GlobalMilesAirlineAPI.Standard;
using GlobalMilesAirlineAPI.Standard.Utilities;


namespace GlobalMilesAirlineAPI.Standard.Models
{
    public class User : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string firstName;
        private string lastName;
        private string mobile;
        private string email;
        private Models.LanguageTypeEnum? language;
        private Models.GenderTypeEnum? gender;
        private string birthday;
        private string nationality;
        private string nationalIdNumber;
        private string academicTitle;
        private string address;
        private string country;
        private string city;
        private string area;
        private string zipCode;
        private string password;

        /// <summary>
        /// First name of the user. Maximum length is 40 characters.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName 
        { 
            get 
            {
                return this.firstName; 
            } 
            set 
            {
                this.firstName = value;
                onPropertyChanged("FirstName");
            }
        }

        /// <summary>
        /// Last name of the user. Maximum length is 40 characters.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName 
        { 
            get 
            {
                return this.lastName; 
            } 
            set 
            {
                this.lastName = value;
                onPropertyChanged("LastName");
            }
        }

        /// <summary>
        /// Mobile phone number of the user It is a unique identifier for users in the system. The format is E.164.
        /// </summary>
        [JsonProperty("mobile")]
        public string Mobile 
        { 
            get 
            {
                return this.mobile; 
            } 
            set 
            {
                this.mobile = value;
                onPropertyChanged("Mobile");
            }
        }

        /// <summary>
        /// Email address of the user.
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// The language of the user. Possible values are 'en' and 'tr'.
        /// </summary>
        [JsonProperty("language", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.LanguageTypeEnum? Language 
        { 
            get 
            {
                return this.language; 
            } 
            set 
            {
                this.language = value;
                onPropertyChanged("Language");
            }
        }

        /// <summary>
        /// Gender of the user. The possible values are 'female', 'male' or 'unknown'.
        /// </summary>
        [JsonProperty("gender", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.GenderTypeEnum? Gender 
        { 
            get 
            {
                return this.gender; 
            } 
            set 
            {
                this.gender = value;
                onPropertyChanged("Gender");
            }
        }

        /// <summary>
        /// Birthday of the user. The possible values are a date with YYYYMMDD formatted or null.
        /// </summary>
        [JsonProperty("birthday")]
        public string Birthday 
        { 
            get 
            {
                return this.birthday; 
            } 
            set 
            {
                this.birthday = value;
                onPropertyChanged("Birthday");
            }
        }

        /// <summary>
        /// Nationality
        /// </summary>
        [JsonProperty("nationality")]
        public string Nationality 
        { 
            get 
            {
                return this.nationality; 
            } 
            set 
            {
                this.nationality = value;
                onPropertyChanged("Nationality");
            }
        }

        /// <summary>
        /// National ID Number
        /// </summary>
        [JsonProperty("national_id_number")]
        public string NationalIdNumber 
        { 
            get 
            {
                return this.nationalIdNumber; 
            } 
            set 
            {
                this.nationalIdNumber = value;
                onPropertyChanged("NationalIdNumber");
            }
        }

        /// <summary>
        /// Academic Title
        /// </summary>
        [JsonProperty("academic_title")]
        public string AcademicTitle 
        { 
            get 
            {
                return this.academicTitle; 
            } 
            set 
            {
                this.academicTitle = value;
                onPropertyChanged("AcademicTitle");
            }
        }

        /// <summary>
        /// Address
        /// </summary>
        [JsonProperty("address")]
        public string Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// Country
        /// </summary>
        [JsonProperty("country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                onPropertyChanged("Country");
            }
        }

        /// <summary>
        /// City
        /// </summary>
        [JsonProperty("city")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// State/County/Province/Region
        /// </summary>
        [JsonProperty("area")]
        public string Area 
        { 
            get 
            {
                return this.area; 
            } 
            set 
            {
                this.area = value;
                onPropertyChanged("Area");
            }
        }

        /// <summary>
        /// Zip Code
        /// </summary>
        [JsonProperty("zip_code")]
        public string ZipCode 
        { 
            get 
            {
                return this.zipCode; 
            } 
            set 
            {
                this.zipCode = value;
                onPropertyChanged("ZipCode");
            }
        }

        /// <summary>
        /// Password
        /// </summary>
        [JsonProperty("password")]
        public string Password 
        { 
            get 
            {
                return this.password; 
            } 
            set 
            {
                this.password = value;
                onPropertyChanged("Password");
            }
        }
    }
} 